### PR TITLE
Add timecard submission

### PR DESCRIPTION
**Pull request by aloeb**
Almost finished submitting and getting timecards on the various timecard views.

@kirbyk I have a question! When editing the timecards, I'm trying to pull all the data from the database into the form. Unfortunately, not all of the data I need is in the timecards database, but rather a combination of that and the workdays database (there is a has_many, belongs_to relationship between the two). What is the best way to populate the form with data from the workday objects? It would be pretty easy if I could edit the form contents directly from the controller, but I'm not sure I can do that easily. Would it make more sense to create subforms for the individual workdays in the create and edit views for the timecard?

### CODE REVIEW

**Comment by kirbyk** [comment]
Can you be a bit more specific. I looked at the Timecard controller and _form and I couldn't figure out what you meant.

**Comment by aloeb** [comment]
Ok, well I completely redid timecard submission because I really didn't like it :+1: 

Although now it only mostly works. When opening a previous timecard it will pull in the values correctly to the form, but when creating and editing, it won't create/edit the associated workday models. Any idea whats going on here?

**Comment by aloeb** [comment]
@kirbyk this should be ready to merge! Everything seems to work!

**Comment by kirbyk** [comment]
:cat:

**Pull request merged**
