### PR TITLE
Create all the timecard stuff

### PR DESCRIPTION
**Pull request by aloeb**
Pull request for issues #12, #18, and #24.

Just opening request for organization. Not ready to merge until comment says otherwise.

### CODE REVIEW

**Comment by aloeb** [comment]
Hey @kirbyk ! I laid out how I think the database should work for timecards. I am pretty inexperienced when it comes to database design though, so could you take a look and let me know what you think? Alternatively, instead of storing M1-Su2 (the days worked) in the database, I guess we could have them stored in files and have the database point to the files. Whichever seems more appropriate. Also, if giving the database more columns is acceptable, we could event replace each M1-Su2 with five more columns. Seems like a lot though, which is why I separated it out into its own table.

Thanks!


- User
 - Has many timecards

- Timecard
 - Has a User
 - Has many Funds (that it is payed from)
  - each correlation between the fund and timecard has the percentage of the timecard paid by that fund (timecards can be paid from multiple funds, I believe)
 - Database columns:

Column | Notes
--------- | ---------
 Pay period | integer
 M1 | id from Workday table (below)
 T1 | id from Workday table
 W1 | id from Workday table
 Th1 | id from Workday table
 F1 | id from Workday table
 S1 | id from Workday table
 Su1 | id from Workday table
 M2 | id from Workday table
 T2 | id from Workday table
 W2 | id from Workday table
 Th2 | id from Workday table
 F2 | id from Workday table
 S2 | id from Workday table
 Su2 | id from Workday table

- Fund
 - Has many Timecards (that it pays to)
 - Database columns:

Column | Notes
--------- | ---------
  company code | string
  "cost center" | string?
  "order" | number
  "WBSE" | string?
  "fund" | number

- Workday
 - This would hold all the different types of hours where each row is a day
 - Database columns:

Column | Notes
--------- | ---------
  Worked Regular Attendance | float
  Vacation | float
  Sick Leave-Employee | float
  Sick Leave-Family | float
  Holiday | float

**Comment by kirbyk** [comment]
This looks good to me. I don't understand the file thing you're talking about. We want to store all of these in the database.

One small thing `Has a User` should be `belongs to a User`.

**Comment by aloeb** [comment]
:+1: Thanks! I'll get to work on that.

**Comment by aloeb** [comment]
Hey @kirbyk , I think everything is ready to merge!

Also, @nzetzl , if you need help understand the timecard model when you go to work on submitting timecards, let me know! It's a little bit complicated, but I think this is the best way to do it.

**Comment by kirbyk** [comment]
:+1:

**Pull request merged**
