### PR TITLE
added order, fund, wbse, cost_center 

### PR DESCRIPTION
**Pull request by CaitlinKennedy**
implements #6 #7 #8  #5

### CODE REVIEW

**Comment by kirbyk** [comment]
@CaitlinKennedy is this ready to merge?

**Comment by CaitlinKennedy** [comment]
yep

**Comment by kirbyk** [comment]
@CaitlinKennedy make those changes and ping me again!

**Comment by CaitlinKennedy** [comment]
@kirbyk  I changed seeds.rb, think its ready now

**Comment by kirbyk** [comment]
You're so close!

**Comment by CaitlinKennedy** [comment]
@kirbyk Better?

**Comment by CaitlinKennedy** [comment]
@kirbyk

**Comment by kirbyk** [comment]
Beautiful. :+1:

**Comment by kirbyk** [comment]
@CaitlinKennedy master has changed such that you'll have merge conflicts, so you can press the nice button to automerge everything.

You'll have to manually merge into master. Let me know if you need help. We can do this tomorrow during the meeting if you wish.

**Pull request merged**
